# Generated by Django 3.0.7 on 2020-08-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_address_line1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_address_line2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_town_or_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
