# Generated by Django 3.0.7 on 2020-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemdetails',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
