# Generated by Django 3.0.7 on 2020-08-22 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_discontinued'),
        ('checkout', '0007_auto_20200726_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product'),
        ),
    ]
