# Generated by Django 3.0.7 on 2020-06-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200617_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_a_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='itinerary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
