# Generated by Django 3.0.7 on 2020-08-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200807_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ImageGallery'),
        ),
    ]
