# Generated by Django 3.0.7 on 2020-06-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200626_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='friendly_name',
        ),
    ]
