# Generated by Django 3.0.7 on 2020-08-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200809_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ImageGallery'),
        ),
    ]
