# Generated by Django 3.0.7 on 2020-06-27 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_imagegallery_friendly_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=254)),
                ('text', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('itinerary_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ItineraryItem')),
            ],
            options={
                'verbose_name_plural': 'itineraries',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Itinerary'),
        ),
    ]
