# Generated by Django 3.0.7 on 2020-06-27 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200627_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='itinerary_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='itinerary',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Itinerary'),
        ),
    ]
