# Generated by Django 3.0.7 on 2020-06-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200629_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='service',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
