# Generated by Django 3.0.7 on 2020-06-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200629_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
